cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
urlpatterns = [
    path('remove/<int:product_id>/', views.CartRemove, name='CartRemove'),
    path('add/<int:product_id>/', views.CartAdd, name='CartAdd'),
    path('clear/', views.CartClear, name='CartClear'),
    path('', views.CartDetail, name='CartDetail')
]

orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.OrderCreate, name='OrderCreate')
]

product_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('<slug:category_slug>/', views.ProductList, name='ProductListByCategory'),
    path('<int:id>/<slug:slug>/', views.ProductDetail, name='ProductDetail'),
    path('', views.ProductList, name='ProductList')

]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


#urlpatterns = i18n_patterns(
urlpatterns = [
    path('admin/', admin.site.urls),
    path('^i18n/', include('django.conf.urls.i18n')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('orders.urls', 'orders'), namespace='orders')),

    #path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('', include(('product_app.urls', 'product_app'), namespace='product_app')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from product_app.models import Product

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product_app.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.utils.translation import get_language

@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    lang = get_language()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html', {'cart': cart, 'lang' : lang})

def CartClear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:CartDetail')

templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.png" %}{% endif %}" class="img-responsive">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input type="submit" value="Обновить">
            </form>
            <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
              {% if lang == 'ru' %}
                  <td class="num">{{ item.price_rub }} руб.</td>
                  <td class="num">{{ item.total_price_rub }} руб.</td>
              {% endif %}
              {% if lang != 'ru' %}
                  <td class="num">{{ item.price_usd }} $.</td>
                  <td class="num">{{ item.total_price_usd }} $.</td>
              {% endif %}

          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
            {% if lang == 'ru' %}
                  <td class="num">{{ cart.get_total_price_rub }} руб.</td>
              {% endif %}
              {% if lang != 'ru' %}
                 <td class="num">{{ cart.get_total_price_usd }} руб.</td>
              {% endif %}

        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "product_app:ProductList"%}" class="btn">Продолжить Шопинг</a>
    <a href="{% url "orders:OrderCreate" %}" class="btn">Оформить заказ</a>
  </p>
{% endblock %}