cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
urlpatterns = [
    path('remove/<int:product_id>/', views.CartRemove, name='CartRemove'),
    path('add/<int:product_id>/', views.CartAdd, name='CartAdd'),
    path('clear/', views.CartClear, name='CartClear'),
    path('', views.CartDetail, name='CartDetail')
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


#urlpatterns = i18n_patterns(
urlpatterns = [
    path('admin/', admin.site.urls),
    path('^i18n/', include('django.conf.urls.i18n')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('orders.urls', 'orders'), namespace='orders')),

    #path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('', include(('product_app.urls', 'product_app'), namespace='product_app')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shop/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <!-- Styles -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
  <section id="header">
  <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}" />
        <select name="language">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% for lang in LANGUAGES %}
                <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected"{% endif %}>
                    {{ lang.1 }} ({{ lang.0 }})
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="Go" />
    </form>
    <div class="top container">
      Мой Онлайн-Магазин
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            Корзина(
            <a href="{% url "cart:CartDetail" %}">
                {{ total_items }}
            </a>)
         {% else %}
              Корзина пустая
        {% endif %}
    {% endwith %}
</div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
    {% block content %}{% endblock %}
  </section>
</body>
</html>